### ISSUE TITLE
Inconsistency in pushing data from Jenkins to elastic search

### ISSUE THREAD

**Issue by raulkumar28** [speedledger/elasticsearch-jenkins#2]
I've noticed that my elastic search server does not get all the Jenkins' builds metadata. Some of the builds' records are missing.
When I look at the Jenkins System Log, I see this : (Note that I've excluded most of the build's metadata below)

" Error when sending build data: Build{number=4402, jobName='test', result='SUCCESS', startTime=1426869781003, duration=54, ... //MORE METADATA of BUILDS here}
java.lang.NullPointerException
	at io.searchbox.core.Index.isOperationSucceed(Index.java:33)
	at io.searchbox.client.AbstractJestClient.createNewElasticSearchResult(AbstractJestClient.java:73)
	at io.searchbox.client.http.JestHttpClient.deserializeResponse(JestHttpClient.java:176)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:70)
	at com.speedledger.measure.jenkins.BuildListener.onCompleted(BuildListener.java:74)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:199)
	at hudson.model.Run.execute(Run.java:1810)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240) "

I looked into BuildListener.java file of the plugin, and this happens to be just an Exception that is caught in the OnCompleted() method.

I'd really appreciate any help with this here.

Thanks,
Rahul

**Comment by marcuslonnberg** [comment]
This looks like it could be a bug in the [Jest](https://github.com/searchbox-io/Jest) library. Can you build the plugin with the latest version of Jest and see if it solves the problem?
Please make a PR if it works.

**Comment by raulkumar28** [comment]
Hey Marcus,

Thanks for the response. I appreciate it.
I'm not sure if elasticsearch plugin uses Jest library. Here's the repository I used to build the plugin : https://github.com/speedledger/elasticsearch-jenkins.git

Could you please let me know what I'm not following here?

Thanks again!

**Comment by marcuslonnberg** [comment]
Yes it is the correct repository.
The Jest dependency is in the pom file. Hopefully it should just be to
update to the latest version without any other code change.

/Marcus

2015-03-31 1:39 GMT+02:00 Rahul Racha <notifications@github.com>:

**Comment by raulkumar28** [comment]
I've tried updating Jest version to 0.1.5 (also tried 0.0.6)
But now, When I try to build the plugin(mvn clean install package -e), I get this compilation error : 

[INFO] --- maven-compiler-plugin:2.5:compile (default-compile) @ elasticsearch-jenkins ---
[INFO] Compiling 4 source files to /Users/builder/Documents/elasticsearch-jenkins/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/builder/Documents/elasticsearch-jenkins/src/main/java/com/speedledger/measure/jenkins/BuildListener.java:[39,15] error: cannot find symbol
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.325 s
[INFO] Finished at: 2015-04-06T13:27:11-07:00
[INFO] Final Memory: 30M/446M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5:compile (default-compile) on project elasticsearch-jenkins: Compilation failure
[ERROR] /Users/builder/Documents/elasticsearch-jenkins/src/main/java/com/speedledger/measure/jenkins/BuildListener.java:[39,15] error: cannot find symbol
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5:compile (default-compile) on project elasticsearch-jenkins: Compilation failure
/Users/builder/Documents/elasticsearch-jenkins/src/main/java/com/speedledger/measure/jenkins/BuildListener.java:[39,15] error: cannot find symbol

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.CompilationFailureException: Compilation failure
/Users/builder/Documents/elasticsearch-jenkins/src/main/java/com/speedledger/measure/jenkins/BuildListener.java:[39,15] error: cannot find symbol

	at org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:729)
	at org.apache.maven.plugin.CompilerMojo.execute(CompilerMojo.java:128)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
[ERROR]

**Comment by marcuslonnberg** [comment]
Seems like ClientConfig have changed name to HttpClientConfig.

If we where still using Jenkins I could have made the change for you, but it is hard when I can't test it.
